services:
  nginx:
    image: nginx:alpine
    ports:
      - 8080:80
    volumes:
      - ./.docker/nginx/conf.d:/etc/nginx/conf.d:ro
  laravel:
    build:
      context: .
      dockerfile: ./.docker/php-fpm/Dockerfile
    volumes:
      - ./laravel:/app

  rabbitmq:
    image: rabbitmq:3-management-alpine
    ports:
      - 15672:15672
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq

  redis:
    image: redis:alpine
    volumes:
      - redis_data:/data
  node:
    image: node:16-alpine
    volumes:
      - ./node:/app
    working_dir: /app
    command: sh -c "/usr/local/bin/npm i --prefix /app && /usr/local/bin/npm run dev --prefix /app"
  db:
    image: mysql:8
    platform: linux/x86_64
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'parking'
      MYSQL_USER: 'parkos_admin'
      MYSQL_PASSWORD: 'l4k0u8x6z2'
      MYSQL_ROOT_PASSWORD: 'l4k0u8x6z2'
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
  redis_data:
  rabbitmq_data:
